services:
  hubme-landing:
    build: .
    container_name: hubme-landing
    ports:
      - "3010:3010"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
