"""Image ingestion via Ollama vision (llava)"""

import base64
import httpx
from pathlib import Path
from .chunker import chunk_text
from typing import List, Dict, Any

OLLAMA_URL = 'http://172.17.0.1:11434'


async def ingest_image(file_path: str, slug: str, source_url: str = None) -> List[Dict[str, Any]]:
  """
  Describe image using Ollama llava model and ingest description as chunk.

  Args:
    file_path: Path to image file (jpg, png, webp)
    slug: Clone slug
    source_url: Optional source URL

  Returns:
    List with single description chunk
  """
  try:
    path = Path(file_path)
    if not path.exists():
      raise FileNotFoundError(f'File not found: {file_path}')

    # Read and encode image
    image_data = path.read_bytes()
    image_base64 = base64.b64encode(image_data).decode('utf-8')

    # Call Ollama llava for description
    async with httpx.AsyncClient(timeout=60.0) as client:
      response = await client.post(
        f'{OLLAMA_URL}/api/generate',
        json={
          'model': 'llava:7b',
          'prompt': 'Describe this image in detail, focusing on key information:',
          'images': [image_base64],
          'stream': False,
        }
      )
      response.raise_for_status()
      data = response.json()
      description = data.get('response', '')

    if not description:
      raise ValueError('No description generated by llava')

    # Chunk description
    chunks = chunk_text(description, chunk_size=500, overlap=50)

    # Add metadata
    for chunk in chunks:
      chunk.update({
        'source_type': 'image',
        'source_url': source_url or f'file://{path.absolute()}',
        'source_title': path.stem,
        'clone_slug': slug,
      })

    return chunks

  except Exception as e:
    print(f'❌ Error ingesting image: {e}')
    raise
